[package]
name = "gui-mad"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
once_cell = "1.19.0"
regex = "1.10.6"
tokio = { version = "1.40.0", features = ["full"] }
ureq = "2.10.1"
